import { NgModule } from '@angular/core';
import {
  MatDatepickerModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatAutocompleteModule,
  MatChipsModule,
  MatIconModule,
  MatSortModule,
  MatTableModule,
  MatPaginatorModule,
  MatSlideToggleModule,
  MatSliderModule,
  MatSelectModule,
  MatNativeDateModule,
  MatRadioModule,
  MatMenuModule,
  MatCheckboxModule,
  MatStepperModule,
  MatBottomSheetModule,
  MatTooltipModule,
  MatDialogModule,
  MatProgressBarModule,
  MatExpansionModule,
  MatDividerModule
} from '@angular/material';
import { DragDropModule } from '@angular/cdk/drag-drop';

@NgModule({
  imports: [
    MatSlideToggleModule,
    MatSliderModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatTableModule,
    MatSortModule,
    MatIconModule,
    MatButtonModule,
    MatRadioModule,
    MatInputModule,
    MatMenuModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatStepperModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatPaginatorModule,
    MatTooltipModule,
    DragDropModule,
    MatDialogModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatDividerModule
  ],
  exports: [
    MatSlideToggleModule,
    MatSliderModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatTableModule,
    MatSortModule,
    MatIconModule,
    MatButtonModule,
    MatRadioModule,
    MatInputModule,
    MatMenuModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatStepperModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatPaginatorModule,
    MatTooltipModule,
    DragDropModule,
    MatDialogModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatDividerModule
  ],

  declarations: []
})
export class AngularMaterialModule {}
